<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class UserController extends AbstractController
{

    protected function render(string $view, array $parameters = [], ?Response $response = null): Response
    {
        $view = "{$view}.html.twig";
        return parent::render($view, $parameters, $response); // TODO: Change the autogenerated stub
    }

    #[Route("/api")]
    public function httpBasicReq(Security $security)
    {
        $result = $security->getUser();

        return $this->json(["user"=>$result->getUserIdentifier()]);
    }

    #[Route("/api/login")]
    public function jsonReq(Security $security)
    {
        $result = $security->getUser();

        return $this->json(["user"=>$result->getUserIdentifier()]);
    }
}
